FROM maven:3.9-eclipse-temurin-21 as BUILD
COPY . /src
WORKDIR /src
RUN mvn install -DskipTests

FROM eclipse-temurin:21-jre-jammy
EXPOSE 8080
WORKDIR /app
ARG JAR=library-0.0.1-SNAPSHOT.jar

COPY --from=BUILD /src/target/$JAR /app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
